# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/sbin/cmake

# The command to remove a file.
RM = /usr/sbin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jacub/gong

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jacub/gong

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/sbin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/sbin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jacub/gong/CMakeFiles /home/jacub/gong//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jacub/gong/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gong

# Build rule for target.
gong: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gong
.PHONY : gong

# fast build rule for target.
gong/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gong.dir/build.make CMakeFiles/gong.dir/build
.PHONY : gong/fast

errors/errors.o: errors/errors.c.o
.PHONY : errors/errors.o

# target to build an object file
errors/errors.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gong.dir/build.make CMakeFiles/gong.dir/errors/errors.c.o
.PHONY : errors/errors.c.o

errors/errors.i: errors/errors.c.i
.PHONY : errors/errors.i

# target to preprocess a source file
errors/errors.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gong.dir/build.make CMakeFiles/gong.dir/errors/errors.c.i
.PHONY : errors/errors.c.i

errors/errors.s: errors/errors.c.s
.PHONY : errors/errors.s

# target to generate assembly for a file
errors/errors.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gong.dir/build.make CMakeFiles/gong.dir/errors/errors.c.s
.PHONY : errors/errors.c.s

lexer/lexer.o: lexer/lexer.c.o
.PHONY : lexer/lexer.o

# target to build an object file
lexer/lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gong.dir/build.make CMakeFiles/gong.dir/lexer/lexer.c.o
.PHONY : lexer/lexer.c.o

lexer/lexer.i: lexer/lexer.c.i
.PHONY : lexer/lexer.i

# target to preprocess a source file
lexer/lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gong.dir/build.make CMakeFiles/gong.dir/lexer/lexer.c.i
.PHONY : lexer/lexer.c.i

lexer/lexer.s: lexer/lexer.c.s
.PHONY : lexer/lexer.s

# target to generate assembly for a file
lexer/lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gong.dir/build.make CMakeFiles/gong.dir/lexer/lexer.c.s
.PHONY : lexer/lexer.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gong.dir/build.make CMakeFiles/gong.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gong.dir/build.make CMakeFiles/gong.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gong.dir/build.make CMakeFiles/gong.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gong"
	@echo "... errors/errors.o"
	@echo "... errors/errors.i"
	@echo "... errors/errors.s"
	@echo "... lexer/lexer.o"
	@echo "... lexer/lexer.i"
	@echo "... lexer/lexer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

